# Generated by Django 3.1.6 on 2021-02-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='eating date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('icecream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.icecream')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
